### PR TITLE
Updated vcpkg baseline for mp11 port fixes

### PR DESCRIPTION
**Pull request by JDuffeyBQ**

### CODE REVIEW

**Comment by jmarquisbq** [comment]
@JDuffeyBQ Mike says you can disable the azure pipelines if you've got these working again so we don't have both going at once.

**Comment by JDuffeyBQ** [comment]
I've disabled them on the azure project now.

**Review by imikejackson — CHANGES_REQUESTED** [review]
Change the directory .azure to .azure_disabled to disable the azure bots.

**Review by imikejackson — APPROVED** [review]

**Comment by imikejackson** [comment]
@JDuffeyBQ didn't read the comments above. This is good to go.

**Pull request merged**
