### PR TITLE
BUG FIX: InitializeData now initializes the entire Z range.

### PR DESCRIPTION
**Pull request by joeykleingers**

### CODE REVIEW

**Comment by JDuffeyBQ** [comment]
@joeykleingers The test also needs to be fixed since it wasn't failing before when it was incorrect. These lines should fix it:
```diff
diff --git a/src/Plugins/ComplexCore/test/InitializeDataTest.cpp b/src/Plugins/ComplexCore/test/InitializeDataTest.cpp
index 2e51c72b..a292fc1a 100644
--- a/src/Plugins/ComplexCore/test/InitializeDataTest.cpp
+++ b/src/Plugins/ComplexCore/test/InitializeDataTest.cpp
@@ -85,13 +85,13 @@ bool DoesRangeSatisfyCondition(const IDataStore& dataStore, const std::array<usi
 }

 template <class T>
-bool DoesRangeEqualValue(const IDataStore& dataStore, const std::array<usize, 3>& dims, uint64 xMin, uint64 yMin, uint64 zMin, uint64 xMax, uint64 yMax, uint64 zMax, float64 expectedValue)
+bool DoesRangeEqualValue(const IDataStore& dataStore, const std::array<usize, 3>& dims, uint64 xMin, uint64 xMax, uint64 yMin, uint64 yMax, uint64 zMin, uint64 zMax, float64 expectedValue)
 {
   return DoesRangeSatisfyCondition<T>(dataStore, dims, xMin, yMin, zMin, xMax, yMax, zMax, [expectedValue](T value) { return value == expectedValue; });
 }

 template <class T>
-bool IsDataWithinInclusiveRange(const IDataStore& dataStore, const std::array<usize, 3>& dims, uint64 xMin, uint64 yMin, uint64 zMin, uint64 xMax, uint64 yMax, uint64 zMax,
+bool IsDataWithinInclusiveRange(const IDataStore& dataStore, const std::array<usize, 3>& dims, uint64 xMin, uint64 xMax, uint64 yMin, uint64 yMax, uint64 zMin, uint64 zMax,
                                 std::pair<float64, float64> range)
 {
   return DoesRangeSatisfyCondition<T>(dataStore, dims, xMin, yMin, zMin, xMax, yMax, zMax, [range](T value) { return value >= range.first && value <= range.second; });
```

**Comment by joeykleingers** [comment]
@JDuffeyBQ There were several other issues with the unit test as well that I fixed... they are detailed in the [8b2ba83](https://github.com/BlueQuartzSoftware/complex/pull/683/commits/8b2ba834b5da51c51e5563d0a19e3332d837bd0a) commit.

**Comment by joeykleingers** [comment]
This is ready for review again.

**Comment by JDuffeyBQ** [comment]
@joeykleingers I made a couple of changes to simplify some of the functions if you take a look.

**Comment by joeykleingers** [comment]
@JDuffeyBQ Yep, it looks good to me.  If you approve it, then I'll merge it in.

**Review by JDuffeyBQ — APPROVED** [review]

**Pull request merged**
