### PR TITLE
Add Parameter to allow selection of a DataArray

### PR DESCRIPTION
**Pull request by imikejackson**
Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

### CODE REVIEW

**Review by mmarineBlueQuartz — APPROVED** [review]
I lean towards method and class documentation should be filled in or not included, but there is nothing wrong with the code.

**Review by JDuffeyBQ — COMMENTED** [review]
Should we add a type option for limiting the which DataArray the user can select? Or do we want to add that later and get this in now?

Otherwise looks good.

**Review by JDuffeyBQ — COMMENTED** [review]
Also maybe we need an API to check if a `DataObject` is a `DataArray`? So we can check that when validating.

**Comment by imikejackson** [comment]
> Also maybe we need an API to check if a `DataObject` is a `DataArray`? So we can check that when validating.

Added a check to make sure it isn't at least a DataGroup. Trying to check for DataArray can't work because DataArray is templated. If DataArray subclassed from something between DataObject and DataArray, like IDataArray, then you could check that. Is there an enumeration that we could maybe check instead? Otherwise merge this in.

**Comment by JDuffeyBQ** [comment]
> 
> 
> > Also maybe we need an API to check if a `DataObject` is a `DataArray`? So we can check that when validating.
> 
> Added a check to make sure it isn't at least a DataGroup. Trying to check for DataArray can't work because DataArray is templated. If DataArray subclassed from something between DataObject and DataArray, like IDataArray, then you could check that. Is there an enumeration that we could maybe check instead? Otherwise merge this in.

I'm not aware of any, but Matthew would know for sure.

**Pull request merged**
