### PR TITLE
[WIP] Test adding filters that are auto generated from current SIMPL

### PR DESCRIPTION
**Pull request by imikejackson**
ConditionalSetValue
CreateDataContainer
CreateGridMontage
CreateStringArray
CropVertexGeometry
DataContainerWriter
ExecuteProcess
FeatureCountDecision
FeatureDataCSVWriter
FindDerivatives
GenerateTiltSeries
GenerateVertexCoordinates
MaskCountDecision
PostSlackMessage
RawBinaryReader
RenameAttributeArray
RenameAttributeMatrix
RenameDataContainer
ReplaceValueInArray
RequiredZThickness
SplitAttributeArray
WriteTriangleGeometry

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

### CODE REVIEW

**Comment by imikejackson** [comment]
DO NOT MERGE THIS. Using the PR to test auto generated code to ensure it will compile on other platforms.

**Comment by imikejackson** [comment]
@JDuffeyBQ Take a look at the filters and see if you agree with what is being generated. If you have seen one filter you have seen them all. Let me know if anything needs to be change.

The generated code was from the perspective of someone outside of the project that is looking at their transformed code for the first time which is why I chose to use explicit types instead of 'auto' in some locations.

**Review by JDuffeyBQ — COMMENTED** [review]
Looks good to me. The only addition that might be nice would be to take the comments from the `IFilter` functions and add them here.

**Comment by imikejackson** [comment]
Done.

**Pull request closed without merging**
