### PR TITLE
Removed clang-format off as it is no longer needed

### PR DESCRIPTION
**Pull request by JDuffeyBQ**

### CODE REVIEW

**Comment by imikejackson** [comment]
What version of CLang Format do I need? This failed on my local machine

**Comment by JDuffeyBQ** [comment]
The CI is using 10.

**Comment by imikejackson** [comment]
I use a slightly newer version of ClangFormat and it still formats that line of code. I think we should just leave it in until we can figure out the differences.

**Comment by JDuffeyBQ** [comment]
Sounds good.

**Pull request closed without merging**
